server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eureka-client
          uri: lb://eureka-client
          predicates:
            - Path=/client/**
          filters:
            - name: AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka